# Generated by Django 5.0.6 on 2024-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome_completo', models.CharField(max_length=40, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=11, verbose_name='Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
