# Generated by Django 5.0.6 on 2024-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_historico_usuario_id_usuario_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='historico',
            field=models.TextField(db_tablespace='usuario_historico', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
