# Generated by Django 5.0.6 on 2024-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_id_usuario_usuario_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
