# Generated by Django 5.0.6 on 2024-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_id_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='historico',
            field=models.TextField(),
        ),
    ]
