# Generated by Django 5.0.6 on 2024-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_usuario_id_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='historico',
            field=models.TextField(blank=True),
        ),
    ]
