# Generated by Django 5.0.6 on 2024-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('nome', models.CharField(max_length=30)),
                ('repeticoes', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
    ]
