# Generated by Django 5.0.6 on 2024-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='id',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
